import type { Node } from '@xyflow/react';

export function exportToArduino(code: string, nodes: Node[]): string {
  let arduino = `// Generated by IoT Studio by Bilota AI\n// https://iot-studio.bilota.ai\n\n`;

  const types = nodes.map((n) => (n.data as { componentType?: string }).componentType || '');
  if (types.some((t) => t === 'dht11'))
    arduino += '#include <DHT.h>\n';
  if (types.some((t) => t === 'servo'))
    arduino += '#include <Servo.h>\n';
  if (types.some((t) => t?.includes('lcd')))
    arduino += '#include <LiquidCrystal.h>\n';
  if (types.some((t) => t?.includes('oled')))
    arduino += '#include <Wire.h>\n#include <Adafruit_SSD1306.h>\n';

  arduino += '\n';

  let transformed = code;
  transformed = transformed.replace(
    /readSensor\("([^"]+)"\)/g,
    'analogRead(A0) /* $1 */'
  );
  transformed = transformed.replace(
    /writeActuator\("([^"]+)",\s*(.*?)\)/g,
    'digitalWrite(13, $2) /* $1 */'
  );
  transformed = transformed.replace(/log\((.*?)\)/g, 'Serial.println($1)');
  transformed = transformed.replace(
    /logData\([^)]+\)/g,
    '/* logData - use Serial for Arduino */'
  );

  const setupMatch = transformed.match(
    /function\s+setup\s*\(\)\s*\{([\s\S]*?)\n\}/
  );
  const loopMatch = transformed.match(
    /function\s+loop\s*\(\)\s*\{([\s\S]*?)\n\}/
  );

  const varSection = transformed.split('function setup')[0]?.trim() || '';
  if (varSection) {
    arduino += varSection.replace(/let |const /g, 'int ') + '\n\n';
  }

  arduino += 'void setup() {\n  Serial.begin(9600);\n';
  arduino += (setupMatch?.[1] || '') + '\n}\n\n';
  arduino += 'void loop() {\n';
  arduino += (loopMatch?.[1] || '') + '\n}\n';

  return arduino;
}

export function downloadArduinoSketch(
  code: string,
  nodes: Node[],
  projectName: string
): void {
  const arduino = exportToArduino(code, nodes);
  const blob = new Blob([arduino], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectName.replace(/[^a-zA-Z0-9-_]/g, '_')}.ino`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
